crud/urls.py
from django.urls import path
from .views import homepage,create,particularData,contact,deleteData,updateData,aboutus


app_name="crud"
urlpatterns = [
    path("",homepage,name="home"),
    path("about/",aboutus,name="about"),
    path("create/",create,name="create"),
    path("<int:id>",particularData,name="particular"),
    path("delete/<int:id>",deleteData,name="delete"),
    path("update/<int:id>",updateData,name="update"),
    path("contacts/",contact,name="contacts"),
]

myproject/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include("crud.urls")),
    path('users/',include("users.urls")),
]

users/urls.py
from django.urls import path
from .views import UserData,loginUser,logoutUser

app_name="users"
urlpatterns = [
    path('register/',UserData,name="user"),
    path('login/',loginUser,name="Login"),
    path('logout/',logoutUser,name="Logout"),
]

crud/models.py
from django.db import models
from django.contrib.auth.models import User


# Create your models here.
class Blog(models.Model):
    user = models.ForeignKey(User,on_delete=models.CASCADE)
    title =  models.CharField(max_length=150)
    subtitle = models.CharField(max_length=200,default="This is the Sub Heading")
    description = models.TextField()


    def __str__(self) -> str:
        return self.title

class Contact(models.Model):
    name =  models.CharField(max_length=150)
    email = models.EmailField()
    message = models.TextField()


    def __str__(self) -> str:
        return self.name
    
    # @classmethod
    # def create(cls,name,message,email):
    #     contact = cls(name=name,message=message,email=email)
    #     return contact

users/models.py
from django.db import models

# Create your models here.

crud/forms.py
from django import forms
from .models import Blog

class BlogForm(forms.ModelForm):
    class Meta:
        model=Blog
        fields='__all__' 

crud/views.py
from django.shortcuts import redirect, render
from .models import Blog, Contact
from .forms import BlogForm
from django.core.paginator import Paginator
from django.core.mail import EmailMessage
from myproject.settings import EMAIL_HOST_USER #replace root with your project name
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

# Create your views here.
def homepage(request):
    # return HttpResponse("Hello, This is Bishal's Project")
    blog = Blog.objects.all()
    paginator = Paginator(blog,2)
    page_number = request.GET.get("page")
    page_obj = paginator.get_page(page_number)
    
    data = request.GET.get("search")
    if data != "" and data is not None:
        searchData = Blog.objects.filter(title__contains=data)
        print(searchData)
        return render(request,"crud/index.html",{"blog":searchData})
    return render(request,"crud/index.html",{"Blogs":page_obj})

def contact(request):
    if request.method == "POST":
        name = request.POST.get("name")
        email = request.POST.get("email")
        message = request.POST.get("message")
        subject = "Wants to Colloborate !!!"
        recipient = "Bishal@test.com","bishal@yopmail.com",
        html_content =render_to_string('crud/email.html',{'name':name,'description':message,'mail':email})
        email=EmailMessage(
            subject,
            html_content,
            EMAIL_HOST_USER,
            recipient
        )


        email.fail_silently=False
        if email!=None:
            email.send()

        crud = Contact(
            name = name,
            email= email,
            message = message
        )
        crud.save()
        print(name,email,message)
        return redirect("crud:home")


    return render(request,"crud/contact.html")

def particularData(request,id):
    blog = Blog.objects.get(id=id)
    return render(request,"crud/post.html",{"blog":blog})

@login_required
def create(request):
    forms = BlogForm(request.POST or None)
    print(forms)
    if(forms.is_valid()):
        forms.save()
        return redirect("crud:home")
    return render(request, "crud/create.html")

def deleteData(request,id):
    deldata = Blog.objects.get(id=id)   
    deldata.delete()
    return redirect('crud:home')


def updateData(request,id):
    blog = Blog.objects.get(id=id)
    forms = BlogForm(request.POST or None,instance=blog)
    context = {
        "forms":forms,
        "title":blog.title,
        "subtitle":blog.subtitle,
        "description":blog.description
    }
    if forms.is_valid():
        forms.save()
        return redirect("crud:home")
    return render(request, "crud/create.html",context)

def aboutus(request):
    return render(request,"crud/about.html")

users/views.py
from django.shortcuts import render,redirect
from django.contrib.auth.models import User
from django.contrib.auth import authenticate, login
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required

# Create your views here.
def UserData(request):
    if request.method == "POST":
        Username = request.POST.get("username")
        Email = request.POST.get("email")
        FirstName = request.POST.get("firstname")
        LastName = request.POST.get("lastname")
        Password = request.POST.get("password")
        ConfirmPassword = request.POST.get("confirmpassword")
        if Password == ConfirmPassword:
            user = User.objects.create_user(
                username=Username,
                email=Email,
                first_name=FirstName,
                last_name=LastName,
                password=Password
            )
            user.save()
            return redirect("crud:home")
        else:
            print("Passowrd validation failed")
    return render(request,"users/Register.html")

def loginUser(request):
    if request.method == "POST":
        username = request.POST.get("username")
        password = request.POST.get("password")
        user = authenticate(request,username=username,password=password)

        if user is not None:
            login(request,user)
            return redirect("crud:home")
        else:
            return redirect("users:Login")
    return render(request,"users/Login.html")

@login_required
def logoutUser(request):
    logout(request)
    return redirect("crud:home")

crud/templates/crud/contact.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('{% static 'assets/img/contact-bg.jpg' %}')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Contact Me</h1>
          <span class="subheading">Have questions? I have answers.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <p>
          Want to get in touch? Fill out the form below to send me a message and
          I will get back to you as soon as possible!
        </p>
        <div class="my-5">
          <form id="contactForm" method="post">
            {%csrf_token%}
            <div class="form-floating">
              <input
                class="form-control"
                id="id_name"
                type="text"
                name="name"
                required
                placeholder="Enter your name..."
              />
              <label for="id_name">Name</label>
              <div class="invalid-feedback" data-sb-feedback="name:required">
                A name is required.
              </div>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                name="email"
                id="id_email"
                type="email"
                required
                placeholder="Enter your email..."
              />
              <label for="id_email">Email address</label>
              <div class="invalid-feedback" data-sb-feedback="email:required">
                An email is required.
              </div>
              <div class="invalid-feedback" data-sb-feedback="email:email">
                Email is not valid.
              </div>
            </div>
            <div class="form-floating">
              <textarea
                class="form-control"
                id="id_message"
                name="message"
                placeholder="Enter your message here..."
                required
                style="height: 12rem"
              ></textarea>
              <label for="message">Message</label>
              <div class="invalid-feedback" data-sb-feedback="message:required">
                A message is required.
              </div>
            </div>
            <br />

            <div class="d-none" id="submitSuccessMessage">
              <div class="text-center mb-3">
                <div class="fw-bolder">Form submission successful!</div>
                To activate this form, sign up at
                <br />
                <a href="https://startbootstrap.com/solution/contact-forms"
                  >https://startbootstrap.com/solution/contact-forms</a
                >
              </div>
            </div>
            <!-- Submit error message-->
            <!---->
            <!-- This is what your users will see when there is-->
            <!-- an error submitting the form-->
            <div class="d-none" id="submitErrorMessage">
              <div class="text-center text-danger mb-3">
                Error sending message!
              </div>
            </div>
            <!-- Submit Button-->
            <button
              class="btn btn-primary text-uppercase "
              id="submitButton"
              type="submit"
            >
              Send
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{%endblock%}

crud/templates/crud/create.html
{%extends 'base.html'%}
{%load static%}
{%block body%}
<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('{% static 'assets/img/contact-bg.jpg'%}')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Create</h1>
          <span class="subheading">Lets create some Information.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <h5>
         Enter your details
        </h5>
        <div class="my-5">
          <form id="contactForm" method="post">
            {%csrf_token%}
            
            <div class="form-floating">
              <input
              class="form-control"
              name="title"
              id="id_title"
              type="text"
              value="{{title}}"
              required
              placeholder="Enter your Title..."
              data-sb-validations="required"
              />
              <label for="id_title">Title</label>
              <div class="invalid-feedback" data-sb-feedback="name:required">
                A title is required.
              </div>
            </div>
            <div class="form-floating">
              <input
              class="form-control"
              name="subtitle"
              id="id_subtitle"
              type="text"
              required
              value="{{subtitle}}"
              placeholder="Enter your Title..."
              data-sb-validations="required"
              />
              <label for="id_subtitle">Subtitle</label>
              <div class="invalid-feedback" data-sb-feedback="name:required">
                A title is required.
              </div>
            </div>
            
            
            <div class="form-floating">
              <textarea
                class="form-control"
                name="description"
                id="id_description"
                placeholder="Enter your message here..."
                required
                style="height: 12rem"
                data-sb-validations="required"
              >{{description}}</textarea>
              <label for="id_description">Write your description</label>
              
            </div>

            <div class="form-floating">
              <input
              class="form-control"
              name="user"
              type="hidden"
              required
              value="{{user.id}}"
              />
            </div>
            <!-- Submit Button-->
            <button
              class="btn btn-primary "
              id="submitButton"
              type="submit"
            >
              Save
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{%endblock%}

crud/templates/crud/createme.html
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="UTF-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>contacts</title>
    <link
      href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/css/bootstrap.min.css"
      rel="stylesheet"
      integrity="sha384-9ndCyUaIbzAi2FUVXJi0CjmCapSmO7SnpJef0486qhLnuZ2cdeRhO02iuK6FUUVM"
      crossorigin="anonymous"
    />
  </head>
  <body>
    <nav class="navbar navbar-expand-lg bg-info">
      <div class="container-fluid">
        <a class="navbar-brand" href="{%url 'crud:home'%}">Data</a>
        <button
          class="navbar-toggler"
          type="button"
          data-bs-toggle="collapse"
          data-bs-target="#navbarSupportedContent"
          aria-controls="navbarSupportedContent"
          aria-expanded="false"
          aria-label="Toggle navigation"
        >
          <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav me-auto mb-2 mb-lg-0">
            <li class="nav-item">
              <a
                class="nav-link active"
                aria-current="page"
                href="{%url 'crud:home'%}"
                >Home</a
              >
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'crud:create' %}">Create</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{%url 'crud:contacts' %}">Contacts</a>
            </li>
          </ul>
          <form class="d-flex" role="search">
            <input
              class="form-control me-2"
              type="search"
              placeholder="Search"
              aria-label="Search"
            />
            <button class="btn btn-success" type="submit">Search</button>
          </form>
        </div>
      </div>
    </nav>
    <div class="alert alert-success alert-dismissible fade show" role="alert">
      <strong>Welcome !</strong> This is a Create  Page.<button
        type="button"
        class="btn-close"
        data-bs-dismiss="alert"
        aria-label="Close"
      ></button>
    </div>
    <div class="container">
        <h1>Django Forms</h1>
        <form  method="post">
            {%csrf_token%}
            {{forms}}
            <button type="submit">save</button>
        </form>

    </div>

    <script
      src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.0/dist/js/bootstrap.bundle.min.js"
      integrity="sha384-geWF76RCwLtnZ8qwWowPQNguL3RmwHVBC9FhGdlKrxdiJJigb/j/68SIy3Te4Bkz"
      crossorigin="anonymous"
    ></script>
  </body>
</html>

crud/templates/crud/email.html
Hello, Bishal

    You got mail from {{name}}.
    
    {{description}}
    
    Therefore, if you want to contact him. His/Her email address is {{mail}}.
    
    --
    Best Regards,
    {{name}}
    

crud/templates/crud/home.html
{%extends 'base.html'%} {%load static%} {%block body%}
<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('{% static 'assets/img/home-bg.jpg'%}')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>HomePage</h1>
          <span class="subheading">This is a Homepage.</span>
        </div>
      </div>
    </div>
  </div>
</header>
<div class="container">
  {%if blog %}
  <h2>{{blog.title}}</h2>
  <h5>{{blog.description}}</h5>

  <a href="{%url 'crud:delete' blog.id %}"
    ><button type="submit" class="btn btn-danger">Delete</button>
  </a>
  <a href="{%url 'crud:update' blog.id %}"
    ><button type="submit" class="btn btn-primary">Update</button>
  </a>

  {%endif%} {%if Blogs%} {%for blog in Blogs %}
  <a
    href="{%url 'crud:particular' blog.id%}"
    style="text-decoration: none; color: black"
  >
    <h2>{{blog.title}}</h2>
  </a>
  <h5>{{blog.description}}</h5>
  {%endfor%} {%endif%}
</div>
{%endblock%}

crud/templates/crud/index.html
{% extends 'base.html'%} {% load static %} {%block body%}
<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('{% static 'assets/img/home-bg.jpg' %}')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="site-heading">
          <h1>BlogSpot</h1>
          <span class="subheading">Place where you can create a Good blog</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<div class="container px-4 px-lg-5">
  <div class="row gx-4 gx-lg-5 justify-content-center">
    <div class="col-md-10 col-lg-8 col-xl-7">
      <!-- Post preview-->
      {%if Blogs%} {%for blog in Blogs %}
      <div class="post-preview">
        <a href="{%url 'crud:particular' blog.id%}">
          <h2 class="post-title">{{blog.title}}</h2>
          <h3 class="post-subtitle">{{blog.subtitle}}</h3>
        </a>
        <p class="post-meta">
          Posted by
          <a href="#!">Start Bootstrap</a>
          on September 24, 2023
        </p>
      </div>
      <hr class="my-4" />
      {%endfor%} {%endif%} {%if blog%} {%for blog in blog%} `
      <div class="post-preview">
        <a href="{%url 'crud:particular' blog.id%}">
          <h2 class="post-title">{{blog.title}}</h2>
          <h3 class="post-subtitle">{{blog.subtitle}}</h3>
        </a>
        <p class="post-meta">
          Posted by
          <a href="#!">Start Bootstrap</a>
          on September 24, 2023
        </p>
      </div>
      <hr class="my-4" />

      {%endfor%} {%endif%}

      {% for contact in page_obj %}
    {# Each "contact" is a Contact model object. #}
    {{ contact.full_name|upper }}<br>
    ...
{% endfor %}

<div class="pagination">
    <span class="step-links">
        {% if Blogs.has_previous %}
            <a href="?page=1">&laquo; first</a>
            <a href="?page={{ Blogs.previous_page_number }}">previous</a>
        {% endif %}

        <span class="current">
            Page {{ Blogs.number }} of {{ Blogs.paginator.num_pages }}.
        </span>

        {% if Blogs.has_next %}
            <a href="?page={{ Blogs.next_page_number }}">next</a>
            <a href="?page={{ Blogs.paginator.num_pages }}">last &raquo;</a>
        {% endif %}
    </span>
</div>

      <!-- Pager-->
      <div class="d-flex justify-content-end mb-4">
        <a class="btn btn-primary text-uppercase" href="#!">Older Posts →</a>
      </div>
    </div>
  </div>
</div>
{%endblock%}

crud/templates/crud/post.html
{%extends 'base.html'%} {%load static%} {%block body%}

<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('{% static 'assets/img/post-bg.jpg'%}')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="post-heading">
          <h1>{{blog.title}}</h1>
          <h2 class="subheading">
            {{blog.subtitle}}
          </h2>
          <span class="meta">
            Posted by
            <a href="#!">Start Bootstrap</a>
            on August 24, 2023
          </span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Post Content-->
<article class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        {{blog.description}}
      </div>
      <div class="col-md-10 col-lg-8 col-xl-7">
        <a href="{%url 'crud:delete' blog.id %}"
    ><button type="submit" class="btn btn-outline-danger btn-sm">Delete</button>
  </a>
  <a href="{%url 'crud:update' blog.id %}"
    ><button type="submit" class="btn btn-outline-primary btn-sm">Update</button>
  </a>
      </div>
    </div>
  </div>
</article>
{%endblock%}

myproject/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta
      name="viewport"
      content="width=device-width, initial-scale=1, shrink-to-fit=no"
    />
    <meta name="description" content="" />
    <meta name="author" content="" />
    <title>Clean Blog - Start Bootstrap Theme</title>
    <link
      rel="icon"
      type="image/x-icon"
      href="{% static 'assets/favicon.ico'%}"
    />
    <!-- Font Awesome icons (free version)-->
    <script
      src="https://use.fontawesome.com/releases/v6.3.0/js/all.js"
      crossorigin="anonymous"
    ></script>
    <!-- Google fonts-->
    <link
      href="https://fonts.googleapis.com/css?family=Lora:400,700,400italic,700italic"
      rel="stylesheet"
      type="text/css"
    />
    <link
      href="https://fonts.googleapis.com/css?family=Open+Sans:300italic,400italic,600italic,700italic,800italic,400,300,600,700,800"
      rel="stylesheet"
      type="text/css"
    />
    <!-- Core theme CSS (includes Bootstrap)-->
    <link href="{% static 'css/styles.css' %}" rel="stylesheet" />
  </head>
  <body>
    {%include 'nav.html'%} {%block body %} {%endblock%} 
    {%include 'footer.html'%}

    <!-- Bootstrap core JS-->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/js/bootstrap.bundle.min.js"></script>
    <!-- Core theme JS-->
    <script src="{%static 'js/scripts.js'%}"></script>
  </body>
</html>

myproject/templates/nav.html
<!-- Navigation-->
<nav class="navbar navbar-expand-lg bg-body-tertiary" id="mainNav">
  <div class="container">
    <a class="navbar-brand" href="{%url 'crud:home' %}">BlogSpot</a>
    <button
      class="navbar-toggler"
      type="button"
      data-bs-toggle="collapse"
      data-bs-target="#navbarResponsive"
      aria-controls="navbarResponsive"
      aria-expanded="false"
      aria-label="Toggle navigation"
    >
      Menu
      <i class="fas fa-bars"></i>
    </button>
    <div class="collapse navbar-collapse" id="navbarResponsive">
      <ul class="navbar-nav ms-auto py-4 py-lg-0">
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'crud:home' %}"
            >Home</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'crud:about'%}"
            >About</a
          >
        </li>
        <li class="nav-item">
          <a
            class="nav-link px-lg-3 py-3 py-lg-4"
            href="{%url 'crud:contacts' %}"
            >Contact</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'crud:create' %}"
            >Create Blog</a
          >
        </li>
        {%if not user.is_authenticated%}
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'users:user' %}"
            >Signup</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="{%url 'users:Login' %}"
            >Signin</a
          >
        </li>
        {%endif%}
        {%if user.is_authenticated%}
        <li class="nav-item">
          <a
            class="nav-link px-lg-3 py-3 py-lg-4"
            href="{%url 'users:Logout' %}"
            >SignOut</a
          >
        </li>
        <li class="nav-item">
          <a class="nav-link px-lg-3 py-3 py-lg-4" href="">Welcome {{user}}</a>
        </li>
        {%endif%}
      </ul>
      <form class="d-flex" method="get">
        {%csrf_token%}
        <input
          class="form-control me-2"
          type="search"
          placeholder="Search"
          name="search"
          aria-label="Search"
        />
        <button class="btn btn-outline-success btn-sm" type="submit">
          Search
        </button>
      </form>
    </div>
  </div>
</nav>

users/templates/users/Login.html
{%extends 'base.html'%} {%load static%} {%block body%}
<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('{% static 'assets/img/login.jpg' %}')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Login </h1>
          <span class="subheading">Let's Login</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <h4>
          Signup to use full features of the web application.
        </h4>
        <div class="my-5">
          <form id="contactForm" method="post">
            {%csrf_token%}
            <div class="form-floating">
              <input
                class="form-control"
                id="id_name"
                type="text"
                name="username"
                required
                placeholder="Enter your name..."
              />
              <label for="id_name">Username</label>
              <div class="invalid-feedback" data-sb-feedback="name:required">
                A name is required.
              </div>
            </div>

            <div class="form-floating">
              <input
                class="form-control"
                name="password"
                id="id_email"
                type="password"
                required
                placeholder="Enter your email..."
              />
              <label for="id_email">Password</label>
            </div>
         

            <!-- Submit Button-->
            <button
              class="btn btn-primary text-uppercase"
              id="submitButton"
              type="submit"
            >
              Send
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{%endblock%}

users/templates/users/Register.html
{%extends 'base.html'%} {%load static%} {%block body%}
<!-- Page Header-->
<header
  class="masthead"
  style="background-image: url('{% static 'assets/img/contact-bg.jpg' %}')"
>
  <div class="container position-relative px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <div class="page-heading">
          <h1>Sign up </h1>
          <span class="subheading">Let's Signup</span>
        </div>
      </div>
    </div>
  </div>
</header>
<!-- Main Content-->
<main class="mb-4">
  <div class="container px-4 px-lg-5">
    <div class="row gx-4 gx-lg-5 justify-content-center">
      <div class="col-md-10 col-lg-8 col-xl-7">
        <h4>
          Signup to use full features of the web application.
        </h4>
        <div class="my-5">
          <form id="contactForm" method="post">
            {%csrf_token%}
            <div class="form-floating">
              <input
                class="form-control"
                id="id_name"
                type="text"
                name="username"
                required
                placeholder="Enter your name..."
              />
              <label for="id_name">Username</label>
              <div class="invalid-feedback" data-sb-feedback="name:required">
                A name is required.
              </div>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                name="email"
                id="id_email"
                type="email"
                required
                placeholder="Enter your email..."
              />
              <label for="id_email">Email address</label>
              <div class="invalid-feedback" data-sb-feedback="email:required">
                An email is required.
              </div>
              <div class="invalid-feedback" data-sb-feedback="email:email">
                Email is not valid.
              </div>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="id_name"
                type="text"
                name="firstname"
                required
                placeholder="Enter your name..."
              />
              <label for="id_name">First Name</label>
              <div class="invalid-feedback" data-sb-feedback="name:required">
                A name is required.
              </div>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                id="id_name"
                type="text"
                name="lastname"
                required
                placeholder="Enter your name..."
              />
              <label for="id_name">Last Name</label>
              <div class="invalid-feedback" data-sb-feedback="name:required">
                A name is required.
              </div>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                name="password"
                id="id_email"
                type="password"
                required
                placeholder="Enter your email..."
              />
              <label for="id_email">Password</label>
            </div>
            <div class="form-floating">
              <input
                class="form-control"
                name="confirmpassword"
                id="id_email"
                type="password"
                required
                placeholder="Enter your email..."
              />
              <label for="id_email">confirm Password</label>
            </div>

            <br />

            <!-- Submit error message-->
            <!---->
            <!-- This is what your users will see when there is-->
            <!-- an error submitting the form-->
            <div class="d-none" id="submitErrorMessage">
              <div class="text-center text-danger mb-3">
                Error sending message!
              </div>
            </div>
            <!-- Submit Button-->
            <button
              class="btn btn-primary text-uppercase"
              id="submitButton"
              type="submit"
            >
              Send
            </button>
          </form>
        </div>
      </div>
    </div>
  </div>
</main>
{%endblock%}